[package]
name = "lean-crypto"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ed25519-dalek = { workspace = true, features = ["rand_core"] }
sha3 = { workspace = true }
rand = { workspace = true }
blake3 = { workspace = true }
hex = { workspace = true }
bs58 = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
