[package]
name = "lean-balancing-index"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
lean-crypto = { path = "../../core/crypto" }
lean-price-index = { path = "../price-index" }
thiserror.workspace = true
serde.workspace = true
chrono.workspace = true
